### ISSUE TITLE
grunt server fails on Windows 7

### ISSUE THREAD

**Issue by HarveyKandola** [rendrjs/rendr-app-template#12] opened 2013-04-22 13:00 UTC
Guys, have tried to invoke `grunt server` on TWO different Windows 7 machines but seem to come up against the same issue:

```
Running "bgShell:runNode" (bgShell) task

Running "handlebars:compile" (handlebars) task
File "app/templates/compiledTemplates.js" created.

Running "rendr_stitch:compile" (rendr_stitch) task
>> '.' is not recognized as an internal or external command,
>> operable program or batch file.
>> Error: Command failed: '.' is not recognized as an internal or external command,
>> operable program or batch file.
Warning: F:\rendr-app-template\node_modules\grunt-rendr-stitch\tmp\bundle\app\app.js isn't in the require path 
Use --force to continue.
```

Works fine on the MAC.

**Comment by jlubawy** [comment] 2013-04-24 08:33
I am having the same issue on Windows 8 (although I suspect it is broken in all versions of Windows).

#### Warning: F:\rendr-app-template\node_modules\grunt-rendr-stitch\tmp\bundle\app\app.js isn't in the require path. Use --force to continue.

This warning is caused by an issue with the `stitch` node module used in the `grunt-rendr-stitch` task.

Currently `stitch` does not have support for Windows file path separators (`\\` rather than `/`) but there are multiple pull requests and [open issues](https://github.com/sstephenson/stitch/pull/41) asking for that support.

None of these requests have been addressed in over a year so in the meantime this [commit](https://github.com/joeyespo/stitch/commit/2e4e6cdb2be204740ca341da787aaac00d347721) should fix the problem and allow you to run `grunt server` (it did for me). Once you have run this CTRL+C out and run `node index.js` to start the server on port `3030` (I don't know if it works this way on Unix machines but the README shows that `grunt server` starts the server as well).

#### >> '.' is not recognized as an internal or external command, operable program or batch file.

I pretty sure I narrowed this issue down to the same `stitch.js` file but I can't seem to pin it down completely. Good news is that if you use the fix for the warning above this error doesn't seem to have any negative affects and you can still run the app on Windows.

Since this is only an app example I would recommend not using `stitch` on Windows (or using Unix) for the time being. That said I'll try to keep investigating this last issue and get back to you if I find anything interesting.

**Comment by HarveyKandola** [comment] 2013-04-24 09:19
Thanks so much for taking the time to respond with a solution. 

Just hope 'stitch' can be updated with your patch.

**Comment by spikebrehm** [comment] 2013-04-25 17:51
Alright, I updated [`grunt-rendr-stitch`](https://github.com/airbnb/grunt-rendr-stitch) to point to the forked version of Stitch with the Windows fix, and I [updated this repo](https://github.com/airbnb/rendr-app-template/commit/8aaad2d3f57a48400034e7d6049a6d32d670fab7) to point to it.  I haven't tested it on Windows yet; can you give a whirl?

**Comment by jlubawy** [comment] 2013-04-25 21:11
Just tested it and it works perfect on Windows now (minus the annoying second error but at least it is usable now).

Thanks @spikebrehm!

**Comment by spikebrehm** [comment] 2013-05-15 21:21
@jlubawy just merged in a PR that should fix that second warning - want to give it a try?

**Closed as completed by spikebrehm** 2013-05-15 21:21 UTC

**Comment by jlubawy** [comment] 2013-05-16 01:50
Thank you that fixed the error.

Just FYI, I did run across another issue when I tried installing rendr on a Windows machine (see https://github.com/airbnb/rendr/issues/34).
