### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by kzap** [rendrjs/rendr-app-template#14] opened 2013-04-27 04:04 UTC
http://127.0.0.1:3030/users_lazy/mojombo gives the above error,

**Comment by spikebrehm** [comment] 2013-04-27 21:27
Doh! That was caused by an upgrade to rendr@0.3.4.  I've fixed in master, give it another try!  Thanks.

**Closed as completed by spikebrehm** 2013-04-27 21:27 UTC
